### ISSUE TITLE
Current/latest Application clone

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/ADC-WW3-NWM-NEMS#22]
Hi Zach,

Please confirm with this:
git clone https://github.com/noaa-ocs-modeling/ADC-WW3-NWM-NEMS.git -b feature/adcirc_v55 --recurse-submodules

you can get the latest application code with all your recent changes.

Thanks,
-Saeed

@zacharyburnettNOAA  @pvelissariou1  @saeed-moghimi-noaa

**Comment by zacharyburnettNOAA** [comment]
can confirm, running
```
git clone https://github.com/noaa-ocs-modeling/ADC-WW3-NWM-NEMS.git -b feature/adcirc_v55 --recurse-submodules
```
works with my credentials
